library: /media/daosyn/daotunes/beets/library.db
directory: /media/daosyn/daotunes/music
plugins:
  - convert
  - duplicates
  - embedart
  - fetchart
  - ftintitle
  - lastgenre
  - lastimport
artist_credit: yes
asciify_paths: yes
fetchart:
  deinterlace: true
  enforce_ratio: true
  maxwidth: 400
  quality: 75
ftintitle:
  drop: yes
import:
  move: yes
lastfm:
  user: daosyn
ui:
  color: yes
